---
iotwin_backend:
  host: 127.0.0.1
  endpoint: '/api/v1'

  kafka_brokers:
  - 'localhost:9091'
  - 'localhost:9092'
  - 'localhost:9093'
  

  pgsql_port: 5432
  pgsql_user: 'username"'
  pgsql_passwod: 'password'


  mqtt_port: 1883
  mqtt_user: 'username'
  mqtt_password: 'password'
  mqtt_topic: '/sensor/data'
